import { NextResponse } from "next/server";

const RUNTIME_ID_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9._:-]{2,79}$/;
const localHosts = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);
const rateWindowMs = 60_000;
const rateKey = "__AI_ATLAS_RUNTIME_RATE_LIMITS__";

type RateEntry = { startedAt: number; count: number };

const rateStore = () => {
  const root = globalThis as typeof globalThis & { [rateKey]?: Map<string, RateEntry> };
  root[rateKey] ??= new Map();
  return root[rateKey];
};

async function digest(value: string) {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return new Uint8Array(bytes);
}

async function secureEqual(left: string, right: string) {
  const [a, b] = await Promise.all([digest(left), digest(right)]);
  if (a.length !== b.length) return false;
  let difference = 0;
  for (let index = 0; index < a.length; index += 1) difference |= a[index] ^ b[index];
  return difference === 0;
}

export async function requireAtlasRuntimeAccess(
  request: Request,
  options: { limitPerMinute?: number } = {},
): Promise<{ runtimeId: string } | { response: NextResponse }> {
  const runtimeId = request.headers.get("x-atlas-runtime-id")?.trim() ?? "";
  if (!RUNTIME_ID_PATTERN.test(runtimeId)) {
    return {
      response: NextResponse.json(
        { error: "유효한 Runtime ID가 필요합니다.", code: "ATLAS_RUNTIME_ID_REQUIRED" },
        { status: 401 },
      ),
    };
  }

  const configuredRuntimeSecret = process.env.ATLAS_INTERNAL_RUNTIME_SECRET?.trim();
  const suppliedRuntimeSecret = request.headers.get("x-atlas-internal-runtime-secret")?.trim() ?? "";
  const integratedRuntime = Boolean(
    configuredRuntimeSecret
    && suppliedRuntimeSecret
    && await secureEqual(suppliedRuntimeSecret, configuredRuntimeSecret),
  );
  const url = new URL(request.url);
  const localDevelopment = process.env.NODE_ENV !== "production" && localHosts.has(url.hostname);
  if (integratedRuntime) {
    // Ephemeral IPC capability generated by the unified launcher. Users never
    // configure or persist this value and it is not an OpenAI credential.
  } else if (!localDevelopment && process.env.ATLAS_TEST_MODE !== "true") {
    return {
      response: NextResponse.json(
        {
          error: "통합 실행기는 내부 IPC 보안 값으로만 접근할 수 있습니다.",
          code: "ATLAS_RUNTIME_AUTH_NOT_CONFIGURED",
        },
        { status: 503 },
      ),
    };
  }

  const now = Date.now();
  const limit = Math.max(1, options.limitPerMinute ?? 180);
  const store = rateStore();
  // Each API route declares its own rate budget. Keying only by Runtime ID
  // made claim, heartbeat, capability, stage and result requests consume one
  // shared counter and could throttle a healthy sequential source sync.
  const rateLimitKey = `${runtimeId}:${request.method}:${url.pathname}`;
  const entry = store.get(rateLimitKey);
  if (!entry || now - entry.startedAt >= rateWindowMs) {
    store.set(rateLimitKey, { startedAt: now, count: 1 });
  } else {
    entry.count += 1;
    if (entry.count > limit) {
      return {
        response: NextResponse.json(
          { error: "통합 런타임 요청 한도를 초과했습니다.", code: "ATLAS_RUNTIME_RATE_LIMITED" },
          { status: 429, headers: { "retry-after": "60" } },
        ),
      };
    }
  }

  return { runtimeId };
}
